import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";

import { Geist, Geist_Mono } from "next/font/google";
import { Tomorrow } from "next/font/google";

import './styles/globals.css';
import './styles/main.css';

const tomorrow = Tomorrow({
  weight: "600",  // Specify the font weight if needed
  subsets: ["latin"], // You can include other subsets as needed
  variable: "--font-tomorrow",  // Optional: Declare a CSS variable for easy use
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${tomorrow.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
